### PR TITLE
fixed :bug: whereby the original logged object was being modified by the

### LINKED ISSUE #46: configureLogFilters appears to be modifying more than log entries
I'm still trying to get to the bottom of it, but it appears calls to `logEx.configureLogFilters` is modifying more than log entries. I discovered it was, for reasons I don't understand yet, also modifying the strings for my http requests in other, unrelated parts of the application. (Subsequently, the modified strings were being rejected by the REST service my application uses.)

If I comment out the calls to `logEx.configureLogFilters`, the REST service works because the http requests remain intact.

gist: https://gist.github.com/eppineda/8d37faf5e40cb3d89e6a947ecd43abb6

filters

(btw, _thank you_ for your fine work on this! I hope to contribute...)

### PR DESCRIPTION
**Pull request by ferronrsmith**
Issue https://github.com/lwhiteley/AngularLogExtender/issues/46
resolves #46

### CODE REVIEW

**Comment by lwhiteley** [comment]
you beat me to the punch... was just looking into it

**Comment by ferronrsmith** [comment]
haha sorry man.

**Comment by lwhiteley** [comment]
yea had the same solution though so no worries.. im fixing the sample app though .. 
has some old express syntax

**Comment by lwhiteley** [comment]
@ferronrsmith 
see if you can run the following command to update the package.json and update this PR
to support express 4 changes

```js
npm install --save-dev body-parser method-override morgan errorhandler
```

**Pull request merged**
